services:
  - type: web
    name: vanuatu-smart-transport
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix ./backend && npm run build
    startCommand: node ./backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
