services:
  - type: web
    name: vanuatu-smart-transport
    env: node
    plan: free
    buildCommand: npm install --prefix ./frontend && npm install --prefix ./backend && npm run build --prefix ./frontend
    startCommand: node ./backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
